apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: metro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: metro
    app.kubernetes.io/part-of: my-app-3
  name: metro
  namespace: karthik-jk-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: metro
status:
  loadBalancer: {}
