apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: metro-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: metro-app
    app.kubernetes.io/part-of: my-app-3
  name: metro-app
  namespace: karthik-jk-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: metro-app
    weight: null
status: {}
